name: deeplearn
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e .  # conda >= 4.4 only
    - python-dotenv>=0.5.1
    - nbval
    - nbdime
  - gsd
  - git
  - openmpi
  - numpy
  - cudatoolkit
  - mpi4py
  - seaborn
  - cmake
  - scipy
  - numba
  - matplotlib
  - setuptools
  - wheel
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - scikit-learn
  - joblib
  - nb_conda
  - pandas
  - requests
  - tqdm
  - python>=3.6

